#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#3a3a3a"
bspc config normal_border_color "#1d1d1d"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle" &
xsetroot -cursor_name left_ptr &

/home/snchart/.config/polybar/launch.sh &
/home/snchart/.fehbg &
picom -b &
dunst &
